name: Deploy to Firebase Functions via github action
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: yarn install && yarn build
        working-directory: functions
      - name: Deploy
        run: npx firebase-tools deploy --only functions --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
